version: '3.8'

services:
  magictv:
    build: .
    container_name: magictv
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Manila
    volumes:
      - ./data:/data
