import React, { useState, useEffect } from 'react';
import { Calendar, Clock } from 'lucide-react';
import { Channel } from '../../types';

export const ScheduleGrid: React.FC = () => {
  const [channels, setChannels] = useState<Channel[]>([]);
  const [selectedChannel, setSelectedChannel] = useState<Channel | null>(null);
  const [schedules, setSchedules] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetch('/api/channels')
      .then(res => res.json())
      .then(data => {
        setChannels(data);
        if (data.length > 0) setSelectedChannel(data[0]);
      })
      .catch(console.error);
  }, []);

  useEffect(() => {
    if (!selectedChannel) return;
    setLoading(true);
    fetch(`/api/channels/${selectedChannel.id}`)
      .then(res => res.json())
      .then(data => {
        setSchedules(data.schedules || []);
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [selectedChannel]);

  const formatTime = (iso: string) => {
    return new Date(iso).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  const formatDate = (iso: string) => {
    return new Date(iso).toLocaleDateString([], { weekday: 'short', month: 'short', day: 'numeric' });
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2.5">
            <Calendar className="w-6 h-6 text-cyan-400" />
            <span>EPG Timetable & Schedule Grid</span>
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Visual program guide for the next 48 hours generated by the scheduling engine.
          </p>
        </div>
      </div>

      {/* Channel selector pills */}
      <div className="flex gap-2 overflow-x-auto pb-2">
        {channels.map(ch => (
          <button
            key={ch.id}
            onClick={() => setSelectedChannel(ch)}
            className={`px-4 py-2 rounded-xl text-sm font-semibold flex items-center gap-2.5 transition-all shrink-0 ${
              selectedChannel?.id === ch.id
                ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/20 font-bold'
                : 'bg-slate-900 text-slate-400 hover:text-white border border-slate-800'
            }`}
          >
            <span className="w-5 h-5 rounded bg-slate-950/40 flex items-center justify-center text-xs">
              {ch.number}
            </span>
            <span>{ch.name}</span>
          </button>
        ))}
      </div>

      {/* Program Schedule Timeline */}
      <div className="bg-slate-900/60 border border-slate-800 rounded-xl overflow-hidden shadow-sm">
        <div className="p-4 border-b border-slate-800 bg-slate-950/40 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg bg-cyan-950 border border-cyan-800/60 flex items-center justify-center text-cyan-300 font-bold text-sm">
              {selectedChannel?.number}
            </div>
            <div>
              <h3 className="font-bold text-white text-base">{selectedChannel?.name}</h3>
              <span className="text-xs text-slate-400">
                Mode: {selectedChannel?.mode === 'slotted' ? `${selectedChannel.slotDuration}m Slotted` : 'Continuous Back-to-Back'}
              </span>
            </div>
          </div>
        </div>

        <div className="p-4">
          {loading ? (
            <div className="py-12 text-center text-slate-500">Loading schedule...</div>
          ) : schedules.length > 0 ? (
            <div className="space-y-3">
              {schedules.map(item => (
                <div
                  key={item.id}
                  className="p-3.5 bg-slate-950/60 border border-slate-800/80 rounded-xl flex flex-col sm:flex-row sm:items-center justify-between gap-4 hover:border-slate-700 transition-colors"
                >
                  <div className="flex items-center space-x-3.5 min-w-0">
                    <div className="w-12 text-center shrink-0">
                      <span className="text-xs font-bold text-cyan-400 font-mono block">
                        {formatTime(item.startTime)}
                      </span>
                      <span className="text-[10px] text-slate-500 font-mono block">
                        {formatTime(item.endTime)}
                      </span>
                    </div>

                    <div className="h-10 w-px bg-slate-800 shrink-0" />

                    <div className="min-w-0">
                      <div className="flex items-center gap-2">
                        <h4 className="text-sm font-bold text-white truncate">{item.title}</h4>
                        {item.mediaItem?.year && (
                          <span className="text-xs text-slate-400">({item.mediaItem.year})</span>
                        )}
                      </div>
                      <p className="text-xs text-slate-400 truncate max-w-xl mt-0.5">
                        {item.mediaItem?.overview || 'No synopsis available.'}
                      </p>
                    </div>
                  </div>

                  <div className="flex items-center gap-3 shrink-0 self-end sm:self-center text-xs text-slate-400">
                    <span className="flex items-center gap-1 font-mono">
                      <Clock className="w-3.5 h-3.5 text-slate-500" />
                      {Math.round(item.duration / 60)}m
                    </span>
                    <span className="px-2 py-0.5 rounded bg-slate-800 text-slate-300">
                      {formatDate(item.startTime)}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="py-12 text-center text-slate-500">
              No programs currently scheduled for this channel.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
